project:
  type: website

website:
  title: "Мой первый сайт"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: presentation.qmd
        text: Сайт за 30 минут

format:
  html:
    theme:
      light: cosmo
      dark: slate
    css: styles.css
    toc: true



